### ISSUE TITLE
[Linux] Unable to load KOTOR 1 saves

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [StarfishXeno/sotor#1]
When i added KOTOR 1 to save editor i get error below (the web version of editor works)
`[ERROR] KotOR 1: "couldn't read items: couldn't read strings: Tlk::read| TLK contains 49301 strings but index 110879 is requested"
`

**Comment by StarfishXeno** [comment]
Sorry for a late reply. 
My version of the game, like yours, has 49k strings and an item referencing 110879 is only realistic for KotOR 2, which has 130k-ish. I could make this a non-error, but there's probably some mix-up or a greater bug going on.
Steam or standalone version of the game?
Are you using any mods? Are there any .uti files in the override folder?

**Comment by TheEpicNoobZilla** [comment]
I rage quit the game due to instability of game, but from what i recall the only mod i had was [community patch](https://deadlystream.com/files/file/1258-kotor-1-community-patch/)

**Comment by StarfishXeno** [comment]
I'm running it on linux with the community patch and some wide-screen patches as well, so we should be about as close as it gets. The built-in data the web version uses is also built from that.
If you remember anything else that could help narrow it down, give me an update. 
I was planning on making an update soon, so if I don't find anything I'll probably just turn this error into a warning.

**Comment by StarfishXeno** [comment]
Managed to reproduce it by copying a bunch of mod files from KotOR2, so probably something along those lines had happened. May be a modder forgot to change some item description.
Going with the "make it a non-error" solution.
