### ISSUE TITLE
Linux case sensitivity

### ISSUE THREAD

**Issue by SomeTroglodyte** [StarfishXeno/sotor#3]
I've got an old installation of TSL migrated a few dozen times by simply copying it. Wine (with gallium-nine) runs this copy just fine, with all mods. Sotor can edit saves by choosing their folder directly, but it cannot read game data.

Of course, case sensitivity is the culprit. Some files are mixed-case, starting with `2DA.bif`.

Now, one could look up some weidu and try its to_lower tool, or fiddle with ciopfs[^1], or format the partition with the appropriate ext4 flag beforehand (which I regrettably forgot), but then...

* While choosing the game folder in the settings, the error message flashes for such a short time that capturing it with a screenshot is impossible. To see it I need to use the reload button.
* [Then there's this line](https://github.com/StarfishXeno/sotor/blob/85ba228e962d8c7f8d7a9017090f465bee83ee11/core/src/util/fs.rs#L14) - why isn't that tool applied to the data folder?

No showstoppers, but teeny weeny minor chances for improvement.

[^1]: Annoying pest - 't would be so nice to just remount some folder, but to use it properly you need to re-copy all your files into an empty ciopfs-mounted path, or else it won't build its index...

**Comment by SomeTroglodyte** [comment]
Actually, the simplest workaround is pointing sotor to a fake game folder containing symlinks as follows:

<details>

```
bob@alice:~/Games/Kotor2$ ls -Rl
.:
total 4
lrwxrwxrwx 1 bob bob   35 2024-11-06 14:41 chitin.key -> /home/bob/C:/Games/KOTOR2/chitin.key
drwxrwxr-x 2 bob bob 4096 2024-11-06 14:54 data
lrwxrwxrwx 1 bob bob   35 2024-11-06 14:41 dialog.tlk -> /home/bob/C:/Games/KOTOR2/dialog.tlk
lrwxrwxrwx 1 bob bob   33 2024-11-06 14:43 override -> /home/bob/C:/Games/KOTOR2/Override
lrwxrwxrwx 1 bob bob   30 2024-11-06 14:41 saves -> /home/bob/C:/Games/KOTOR2/Saves
lrwxrwxrwx 1 bob bob   37 2024-11-06 14:41 swkotor2.exe -> /home/bob/C:/Games/KOTOR2/swkotor2.exe

./data:
total 0
lrwxrwxrwx 1 bob bob 37 2024-11-06 14:40 2da.bif -> /home/bob/C:/Games/KOTOR2/data/2DA.bif
lrwxrwxrwx 1 bob bob 43 2024-11-06 14:40 templates.bif -> /home/bob/C:/Games/KOTOR2/data/Templates.bif
```

.. that's enough, none of the other bif's or folders seem to be read.
</details>

And thanks for such a cute modern editor.

**Comment by StarfishXeno** [comment]
These games have too many damn versions, can't even assume basic file names
Try this build, if it works without symlinks I'll make a release
[sotor.zip](https://github.com/user-attachments/files/17648856/sotor.zip)

**Comment by SomeTroglodyte** [comment]
> if it works without symlinks

It does. :+1: 

> games have too many damn versions

Nah, it's a problem of education. Windows made it too easy for programmers _not_ to learn _consistency_, even if the early Win32 technet dox said to never rely on specific filesystem properties, and the [call to query those](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumeinformationa) was final in the first sold NT 3.1 versions and hasn't changed much since...
